// <auto-generated />
using System;
using ImmoPlus.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImmoPlus.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913201014_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ImmoPlus.Api.Models.Appartement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BailleurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponible")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DureeAvanceExigee")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DureeMaxMois")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("LoyerMensuel")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrixParNuit")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeOffre")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BailleurId");

                    b.ToTable("Appartements");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.Candidature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppartementId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateSoumission")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTraitement")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocataireId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotifRefus")
                        .HasColumnType("TEXT");

                    b.Property<int>("SituationProfessionnelle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppartementId");

                    b.HasIndex("LocataireId");

                    b.ToTable("Candidatures");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidatureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheminStockage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpload")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomFichierOriginal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Proprietaire")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TailleOctets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeDocument")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CandidatureId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.FinancementLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ApportInitial")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("DureeMois")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontantARembourser")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantMensualite")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("NombreMensualites")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TauxFrais")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("FinancementLocations");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.Garant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidatureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SituationProfessionnelle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidatureId")
                        .IsUnique();

                    b.ToTable("Garants");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppartementId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CandidatureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocataireId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppartementId");

                    b.HasIndex("CandidatureId");

                    b.HasIndex("LocataireId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.Mensualite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("TEXT");

                    b.Property<int>("FinancementLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontantDu")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantPaye")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroEcheance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FinancementLocationId");

                    b.ToTable("Mensualites");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MensualiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModePaiement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Montant")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MensualiteId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppartementId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateArrivee")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateDepart")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocataireId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontantTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppartementId");

                    b.HasIndex("LocataireId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.Appartement", b =>
                {
                    b.HasOne("ImmoPlus.Api.Models.Utilisateur", "Bailleur")
                        .WithMany("Appartements")
                        .HasForeignKey("BailleurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bailleur");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.Candidature", b =>
                {
                    b.HasOne("ImmoPlus.Api.Models.Appartement", "Appartement")
                        .WithMany("Candidatures")
                        .HasForeignKey("AppartementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImmoPlus.Api.Models.Utilisateur", "Locataire")
                        .WithMany("Candidatures")
                        .HasForeignKey("LocataireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appartement");

                    b.Navigation("Locataire");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.Document", b =>
                {
                    b.HasOne("ImmoPlus.Api.Models.Candidature", "Candidature")
                        .WithMany("Documents")
                        .HasForeignKey("CandidatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidature");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.FinancementLocation", b =>
                {
                    b.HasOne("ImmoPlus.Api.Models.Location", "Location")
                        .WithOne("FinancementLocation")
                        .HasForeignKey("ImmoPlus.Api.Models.FinancementLocation", "LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.Garant", b =>
                {
                    b.HasOne("ImmoPlus.Api.Models.Candidature", "Candidature")
                        .WithOne("Garant")
                        .HasForeignKey("ImmoPlus.Api.Models.Garant", "CandidatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidature");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.Location", b =>
                {
                    b.HasOne("ImmoPlus.Api.Models.Appartement", "Appartement")
                        .WithMany("Locations")
                        .HasForeignKey("AppartementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImmoPlus.Api.Models.Candidature", "Candidature")
                        .WithMany()
                        .HasForeignKey("CandidatureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ImmoPlus.Api.Models.Utilisateur", "Locataire")
                        .WithMany("Locations")
                        .HasForeignKey("LocataireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appartement");

                    b.Navigation("Candidature");

                    b.Navigation("Locataire");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.Mensualite", b =>
                {
                    b.HasOne("ImmoPlus.Api.Models.FinancementLocation", "FinancementLocation")
                        .WithMany("Mensualites")
                        .HasForeignKey("FinancementLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancementLocation");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.Paiement", b =>
                {
                    b.HasOne("ImmoPlus.Api.Models.Mensualite", "Mensualite")
                        .WithMany("Paiements")
                        .HasForeignKey("MensualiteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ImmoPlus.Api.Models.Reservation", "Reservation")
                        .WithMany("Paiements")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Mensualite");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.Reservation", b =>
                {
                    b.HasOne("ImmoPlus.Api.Models.Appartement", "Appartement")
                        .WithMany("Reservations")
                        .HasForeignKey("AppartementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImmoPlus.Api.Models.Utilisateur", "Locataire")
                        .WithMany("Reservations")
                        .HasForeignKey("LocataireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appartement");

                    b.Navigation("Locataire");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.Appartement", b =>
                {
                    b.Navigation("Candidatures");

                    b.Navigation("Locations");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.Candidature", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Garant");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.FinancementLocation", b =>
                {
                    b.Navigation("Mensualites");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.Location", b =>
                {
                    b.Navigation("FinancementLocation");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.Mensualite", b =>
                {
                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.Reservation", b =>
                {
                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("ImmoPlus.Api.Models.Utilisateur", b =>
                {
                    b.Navigation("Appartements");

                    b.Navigation("Candidatures");

                    b.Navigation("Locations");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
